// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTWFAtnzwHhGRWk9ozDQuVBjzdbTTbnrU',
    appId: '1:75910888144:web:79ca282ccd249a3a933cd5',
    messagingSenderId: '75910888144',
    projectId: 'oasis-form-checker',
    authDomain: 'oasis-form-checker.firebaseapp.com',
    storageBucket: 'oasis-form-checker.appspot.com',
    measurementId: 'G-5XX9GG8B7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnfg5_D_W5hVexaPYWX7KW9PhYEp-ZZHI',
    appId: '1:75910888144:android:b51baa6d13d73fa0933cd5',
    messagingSenderId: '75910888144',
    projectId: 'oasis-form-checker',
    storageBucket: 'oasis-form-checker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4Eg-pzUpPMNNW2ZvqJXG5k605o0gemk',
    appId: '1:75910888144:ios:5ef9d87da8dc417a933cd5',
    messagingSenderId: '75910888144',
    projectId: 'oasis-form-checker',
    storageBucket: 'oasis-form-checker.appspot.com',
    iosClientId: '75910888144-jlqeao3o5dqpa3prm5tf6nlck961cg64.apps.googleusercontent.com',
    iosBundleId: 'com.example.oasisFormsChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4Eg-pzUpPMNNW2ZvqJXG5k605o0gemk',
    appId: '1:75910888144:ios:9107be311949d71b933cd5',
    messagingSenderId: '75910888144',
    projectId: 'oasis-form-checker',
    storageBucket: 'oasis-form-checker.appspot.com',
    iosClientId: '75910888144-sm99j4n0tb0o41ep6i62a0d46jq1kjno.apps.googleusercontent.com',
    iosBundleId: 'com.example.oasisFormsChecker.RunnerTests',
  );
}
